    <h2><?php echo $title?></h2>

    <script type="text/javascript" src="js/validationCourrier.js"></script>
    <script type="text/javascript" src="js/libs/jquery-1.7.1.js"></script>
    
    <div class="well" style="padding: 10px 10px;">
    <br /><br />
    <form id="contactform" method="post" action="/controlleurs/traitementEnvoiCourriel.php" onSubmit="return validationContact()"> 

		<div class="clearfix">
      <label id='name_label' for="name">Name</label>
      <div class="input">
        <?php
					if(isset($page['params']['name'])){
						echo "<input type='text' id=name name=name placeholder='First and last name' required tabindex='1' value='".urldecode($page['params']['email'])."' />";
					}else{
						echo "<input type='text' id=name name=name placeholder='First and last name' required tabindex='1' />";
					}
				?>
      </div>
    </div>    			
		<div class="clearfix">
      <label id='email_label' for="email">Email</label>
      <div class="input">
        <?php
				if(isset($page['params']['email'])){
					echo '<input type="text" id=email name=email placeholder="example@domain.com" required tabindex="2" value="'.urldecode($page['params']['email']).'" />';
				}else{
					echo '<input type="text" id=email name=email placeholder="example@domain.com" required tabindex="2" /> ';
				}
				?>
      </div>
    </div>    
    <div class="clearfix">
      <label id='message_label' for="message">Your Message</label>
      <div class="input">
		    <textarea name=message id=message tabindex="4" cols="80" rows="5" required><?php if(isset($page['params']['message'])){echo urldecode($page['params']['message']);}?></textarea>
      </div>
    </div>
		
		<div class="clearfix" style="padding: 14px 200px;">
    	<input class="btn primary" name="submit" type="submit" id="submit" tabindex="5" value="Me contacter"  /> 
    </div>
    </form>
    
    <br /><br />
    		
		<div id='contactform_success'></div>
		<?php
		if(isset($page['params']['envoiDuMessage'])){
			if($page['params']['envoiDuMessage'] == 'oui'){
				echo "<p>Votre message as &eacute;t&eacute; correctement transmis. Vous receverez une r&eacute;ponse dans les prochains jours.</p>";
			}else{
				echo "<p>Votre Message n'as pas &eacute;t&eacute; transmis. Veuillez v&eacute;rifiez les informations que vous avez saisies ...</p>";
			}
		}
		?>
	</div>