	<?php include INC_PATH . $translationFolder . DIRECTORY_SEPARATOR .'header.php';?>
	
	<?php include INC_PATH . $translationFolder . DIRECTORY_SEPARATOR .'menu_codage.php';?>
	
  <!--
  <header>
		<h2>Ceci est le header de la page <?php echo $page['name'] ?></h2>
  </header>
  -->
	
	<br /><br /><br />
    <?php echo $content ?>
	<br /><br /><br />
	
  <!--
  <footer>
		<h2>Ceci est le footer de la page <?php echo $page['name'] ?></h2>
  </footer>
  -->
  
  
	<?php include INC_PATH . $translationFolder . DIRECTORY_SEPARATOR .'footer.php';?>
    
