
<table border="0" width="310" align="center" cellpadding="10">
  <tr>
	<th colspan="2">
	    <h2><?php echo $title?></h2>
    	<br />
    	Emmanuel ROY
	</th>
	</tr>
	<tr>
		<td colspan="2">
			31B, avenue de l'Observatoire
			<br />
			R&eacute;sidence LE GALLIL&Eacute;
			<br />
			25000 BESAN&Ccedil;ON
		</td>
	</tr>
	<tr>
		<td>
		Tel:
		<br />
		06 62 10 57 00
		</td>
		<td>
		Courriel:
		<br />
		<a href="emmanuel11.roy@gmail.com">emmanuel11.roy@gmail.com</a>
		<br />
		<a href="emmanuel11.roy@laposte.net">emmanuel11.roy@laposte.net</a>
		</td>
	</tr>
	<tr>
		<td>04/10/1982</td><td>Permis B</td> 
	</tr>
	<tr>
	<td colspan="2">
	<br /><br /><br />
	<h2>FORMATION :</h2>
	<hr>
	<table border="0" width="100%" cellspacing="20">
	<tr>
		<td>2014-2018</td>
		<td>Création d'un livre intéractif à choix multiples
			<br />
			<a href='http://villededragons.fr/'> Ville de Dragons&copy; </a>
			<br />
			&nbsp;<b>Réalisation Technique:</b>
			<br />			
			 &nbsp; - Modèle-Vue-Controlleur spécifique à l'application
			 <br />
			 &nbsp; - Multiples compte de lecteur
			 <br />
			 &nbsp; - Travail avec des scénaristes
			 <br />
			 &nbsp; - Intégration des textes écrits
			 <br />
			 &nbsp; - Possibilité d'intégrer plusieurs livres-histoire et de les lier entre-elles
			 <br />
			 &nbsp; - Gestion des affichages Mobile(paysage,portrait), Tablet, Bureau
			 <br />
			 &nbsp; - Mini-applications au sein du livre: Combat, mini-jeu
			 <br />
			 &nbsp; - Un dessin pour chaque paragraphe de choix
			 <br />
			 &nbsp; - Mini-jeu TI89 réalisé en 2000 émulé en Javascript accessible depuis la page d'accueil
  	</td>
	</tr>
	<tr>
		<td>2012</td>
		<td>Professionalisation ( <a href='http://ip-formation.com/'> IP-Formation - Lyon </a> ) en alternance ( <a href='http://www.evolutis.fr/'>Evolutis - Crolles</a> )
			<br />
			&nbsp; - Création de box HTML/CSS
			<br />
			&nbsp; - Decouverte de Magento v1.7 et d&eacute;veloppement d'une base de developpement pour des pages d'administrations d'un module d'administration Magento dont le nom de code est:<b><code>Haingo</code> Import</b> )
			<br />
			&nbsp; - D&eacute;couverte des sch&eacute;mas de programmation historique de PHP ( de 1991 &agrave; aujourd'hui. )
		</td>
	</tr>
	<tr>
		<td>2009-2014</td>
		<td>Gestion et cr&eacute;ation d'une entreprise en auto-entrepreneur: <a href='http://infoartsmedia.fr'>Info[ARTS]Media</a>
			<br />
			&nbsp; - Administration [BackOffice] :<a href='http://infoartsmedia.com'>Info[ARTS]Media [comptes clients]</a>
			<br /><br />
			&nbsp; - Visualisation [FrontOffice] : Créations de Vitri'net en PHP4.0 / MySql / CSS / Javascript (MooTools)
			<br />
			&nbsp;&nbsp;&nbsp; <u>Exemple:</u> <a href='http://trooltower.infoartsmedia.fr'>Vitrine d'artiste pour un objet non-commun la TroolTOWER</a>
			<br />
			&nbsp;&nbsp;&nbsp; <u>Exemple:</u> <a href='http://comme-un-elan.besancon25.fr'>Vitrine d'association de collecte des paroles publique</a>
			<br /><br />
			&nbsp; - Creation d'une plate-Forme de Blogging communautaire: <a href='http://besancon25.info'>http://besancon25.fr [B25]</a>
			<br />
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Site en trois extension de nom de domaine:
			<br />
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Petites-Anonces ( <a href='http://besancon25.com/index.php'>.com</a> ),
			<br />
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Agenda interactif ( <a href='http://besancon25.net/index.php'>.net</a> ),
			<br />
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Blogging Communautaire ( <a href='http://besancon25.fr'>.fr</a> )
			<br />
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ** Avec un <a href='http://wikini.besancon25.fr'>Wikini explicatif.</a>
			</td>
	</tr>
	<tr>
		<td>2004-2009</td>
		<td>Mod&eacute;lisation et R&eacute;vision des langages en Licence informatique &agrave; l'UFR ST de Besan&ccedil;on,</td>
	</tr>
	<tr>
		<td>2001-2004</td>
		<td>Conception et r&eacute;alisation de produits multim&eacute;dia &agrave; l'IUT  Services et R&eacute;seaux de Communication de Montb&eacute;liard,</td>
	</tr>
	<tr>
		<td>2000-2001</td>
		<td>1ere ann&eacute;e en classe pr&eacute;paratoire aux grandes &eacute;coles à l'Universit&eacute; de Technologie de Belfort-Montbéliard (UTBM),</td>
	</tr>
	<tr>
		<td>Année 2000</td>
		<td>Obtention d'un baccalaur&eacute;at Scientifique option Math&eacute;matiques et Sciences de l'ing&eacute;nieur, Mention Assez Bien,</td>
	</tr>
	<tr>
		<td>Langues</td>
		<td>Anglais : Lu, &Eacute;crit, Parl&eacute; ;<br />Allemand : Niveau Bac</td>
	</tr>
	</table>
	<br /><br />
	<h2>EXP&Eacute;RIENCE :</h2>
	<hr>
	<ul>
	<li><b>2016</b> - Stage d'intégration <font style='font-size: 10px;'>(D&eacute;couverte d'Entreprise )</font> chez SkinSoft (Besançon)<br /> D&eacute;couverte de Maven et extJS, travail en Pair programming, d&eacute;boggage script PHP</li>
	<li><b>2016</b> - Stage d'intégration <font style='font-size: 10px;'>(D&eacute;couverte d'Entreprise )</font> chez APROGSYS (Besançon)<br /> R&eacute;daction d'un script BASH pour des tests sur une plate-forme PHP, cr&eacute;ation d'un site internet pour un client</li>
	<li><b>2010</b> - Stage Professionnel <font style='font-size: 10px;'>(D&eacute;couverte d'Entreprise &Eacute;trang&egrave;re)</font> chez Trin&ocirc;me.inc (Canada - Province Qu&eacute;bec - Montr&eacute;al)<br /> D&eacute;bogguage en langage FLEX (Macromedia) pour le site 3etMoi / MyLifeMe</li>
	<li><b>2009</b> - Stage de fin de Licence Informatique au sein de l'EMF1 (Etat-Major de Besan&ccedil;on)<br/>Refonte / Migration d'une site PHP en XML/XSLT/JSP</li>
	<li><b>2001</b> - Stage ouvrier au sein de l'entreprise PSA Peugeot-Citro&euml;n &agrave; Sochaux,</li>
	<li>Design et cr&eacute;ation de divers graphismes pour quelques associations,</li>
	<li>Cr&eacute;ations de sites simples pour diff&eacute;rentes agences,</li>
	<li>Illustrations, logos, ic&ocirc;nes pour diverses utilisations :     Vitrophanies, flyers,...</li>
	</ul>
	<br /><br />
	<h2>LANGAGES INFORMATIQUES ABORDES</h2>
	<hr>
	<ul>
	<li>Langages Webs: HTML5, CSS3, JavaScript (ECMA - JQuery), PHP7 ;</li>
	<li>Langages objets: Java, C++ ;</li>
	<li>Langages formels: Scheme, Prolog ;</li>
	<li>Langages Syst&egrave;mes: C, Bash ;</li>
	<li>Langages Propriétaires: Flex, ActionScript 2.0/3.0, Director, AuthorWare ;</li>
	</ul>
	<br /><br />
	<h2>REALISATIONS :</h2>
	<hr>
	<ul>
	<li>Livre interactif en flash,</li>
	<li>CD interactif sur le film « The Matrix »,<br/> Utilisation de Photoshop / Gimp ; Illustrator / InkScape</li>
	<li>Agenda journalier/Mensuel interactif,</li>
	<li>Site personnel interne Web 1.0 et 2.0,</li>
	<li>Mise en Page d'un 'zine de vacances - VoiLA ( 1er exemplaire )</li>
	<li>Montages photos,</li>
	<li>Illustrations personnelles,</li>
	<li>Animations artistiques.</li>
	<li>Cr&eacute;ation de 3 Objets Multimédia (Une BOX-serveur, une PLV et un Cadre Numérique)</li>
	</ul>
	<br /><br />
	<h2>TRAVAIL TEMPORAIRE :</h2>
	<hr>
	<ul>
	<li>Animateur dans une colonie de vacances pour Poly-Handicap&eacute;s au Domaine de Suech <font style='font-size: 10px;'>du 01/08/10 au 13/08/10</font></li>
	<li>Standardiste &agrave; l'accueil clientèle des Galleries LAFAYETTE de Besan&ccedil;on <font style='font-size: 10px;'>du 02/12/09 au 12/12/09</font>,</li>
	<li>Agent d'entretien, Concierge, Gardien Remplaçant de la m&eacute;diath&egrave;que Pierre-Bayle Besançon <font style='font-size: 10px;'>dur&eacute;e : 1an</font>,</li>
	<li>Aide cuisine dans un restaurant (mise en place d'entrée, préparation des aliments),</li>
	<li>Mise en rayon, chez « Monsieur 2 Euros » et chez Carrefour,<br />
	<li>Retour des invendus au FORUM Besançon,</li>
	<li>Vente de produits multim&eacute;dia au FORUM Besançon,</li>
	<li>Distribution de journaux chez ADREXO Besançon,</li>
	<li>Ramassage des abricots à MERCUROL (Dr&ocirc;me),</li>
	<li>Plongeur au CROUS Montb&eacute;liard et Besançon.</li>
	</ul>
	<br /><br />
	<h2>CENTRES D'INTER&Ecirc;TS :</h2>
	<hr>
	<ul>
	<li>Dessins,</li>
	<li>Illustrations au crayon de papier,</li>
	<li>Photographies (portraits, paysages, exp&eacute;rimentales, macros),</li>
	<li>Sports Extr&ecirc;mes (snow-board, VTT, roller, ...).</li>
	</ul>
	</td>	
	</tr>
	<tr>
	<td>
</table>
